### ISSUE TITLE
Sprint #1

### ISSUE THREAD

**Issue by piqus** [piqus/windows-tweak-tool#1]
![text3348](https://cloud.githubusercontent.com/assets/3073499/9260811/66ae87bc-420a-11e5-8470-81d70b1c8d88.png)

# Sprint 1

* [X] Bootstrap a application based on *Universal App Platform* 
* [x] Design simple GUI with default styled form controls
* [x] Attach a git submodule of https://github.com/nathan-alden/windows-10-tracking
* [ ] Execute PowerShell commands from a JS GUI
* [ ] Currently when executing any command show a *terminal* window or progress bar.
* [ ] Execute commands from submodule

## Next

* [ ] Prepare and investigate merging with https://github.com/nathan-alden/windows-10-tracking
* [ ] Migrate to electron instead of UAP (confirmed 14.08.2015).

**Comment by Cyberzwerg** [comment]
You could use electron for the GUI .. Would be quicker (to develop) most likely..

**Comment by piqus** [comment]
Surely it will, but Universal App Platform with C# looks also promising and have nice backend to run Windows powershell commands and functionality (they're almost the same) - *let's kill the beast with his own weapon*. However, atom-shell/electron is also good choice - almost everybody on GitHub knows a JS, so it will be be easier to contribute to this project and everything is able to hack there (starting from UI, ending on backend), plus it is open sourced like a boss (we're sure there isn't any hook or something which tracks us).

I will investigate this issue and try to choose better platform, but first I have to hack some C# code and release first GUI app for https://github.com/nathan-alden/windows-10-tracking, then probably I will migrate to electron.

**Comment by piqus** [comment]
Oh, I added @nathan-alden as Collaborator. As I said in `README.md`: I am going to merge some ps-scripts which are great to configure low-level setting of Windows OS and his project is fabulous. Additionally I will need a support from Windows10 users and developers to provide better quality of this app.

**Comment by Cyberzwerg** [comment]
This could be expanded to a complete tool set for shell commands, to configure all kinds of hidden features... *starts dreaming*

**Comment by piqus** [comment]
Haha, It is my dream too! :+1:

**Comment by Cyberzwerg** [comment]
:+1:

**Comment by piqus** [comment]
#3 This project joins https://github.com/Plugger-io/plugger

PS. Sorry for not informing you (even briefly) about progress of this project but we were in high development pace :palm_tree:
